836 skjerming rest api med auth
navikt/tiltakspenger-skjerming pull request #178
Opened 2024-05-03 06:20 UTC by sneha-d-desai

## Beskrivelse

- La til azure routes
- La til azure auth
- Flyttet base url config funksjonen fra client til configuration file
- Flyttet configuration file til auth mappe
- Gjorde tilsvarende endringer i test 
- La til inbound rules til nais.yaml
- Slettet rapids and rivers kode

2024-05-03 06:22 UTC, sneha-d-desai commented
![](https://github.trello.services/images/mini-trello-icon.png) [Legge til routes til tiltakspenger-skjerming](https://trello.com/c/WASnEmx2/836-legge-til-routes-til-tiltakspenger-skjerming)

2024-05-06 08:59 UTC, KarlEvaldNav requested changes
Noen småfikser, ellers ser den knall ut! 🎉 

Co-reviewed-by: erlendev <Erlend.Edvardsen.Vige@nav.no>

2024-05-06 08:59 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/auth/Configuration.kt
> +            "stsUrl" to "",
Skal denne være tom i prod?

2024-05-06 08:59 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/auth/Configuration.kt
> +            "SERVICEUSER_TPTS_PASSWORD" to System.getenv("SERVICEUSER_TPTS_PASSWORD"),
Dette er kafka-greier og kan fjernes
```suggestion
```

2024-05-06 08:59 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/service/SkjermingService.kt
> +                        skjerming = skjermingKlient.erSkjermetPerson(ident, callId),
Er det meningen at barna skal ha skjermingsverdien til foreldrene? Eller skal den sjekke på ‘it’ som ident?

2024-05-06 08:59 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/service/SkjermingService.kt
> +) {
Denne klassen burde testes!

2024-05-06 08:59 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/Application.kt
> +    }
Dette burde det skrives en test på så vi vet at det fungerer som det skal

2024-05-07 07:45 UTC, KarlEvaldNav commented on src/main/kotlin/no/nav/tiltakspenger/skjerming/service/SkjermingService.kt
> +                        skjerming = skjermingKlient.erSkjermetPerson(ident, callId),
Sjekket koden som allerede eksisterte på dette, og det ser ut som at dette er en bug. Fikser 👍

2024-05-15 07:19 UTC, merged